<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bc</string>
	</array>
	<key>name</key>
	<string>Beyond Compare</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.beyond-compare</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:^\s+)?(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.beyond-compare</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(attrib|beep|collapse|compare|copy|copyto|criteria|data-report|delete|expand|file-report|filter|folder-report|hex-report|load|log|move|mp3-report|option|picture-report|registry-report|rename|select|snapshot|sync|text-report|touch|version-report)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.beyond-compare</string>
				</dict>
			</dict>
			<key>end</key>
			<string>[^&amp;]$</string>
			<key>name</key>
			<string>meta.statement.beyond-compare</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.beyond-compare</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.beyond-compare</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.beyond-compare</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.beyond-compare</string>
</dict>
</plist>