<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>srt</string>
	</array>
	<key>name</key>
	<string>Subrip</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;i&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.tag.begin.subrip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/i&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.tag.end.subrip</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.italic.subrip</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>&lt;b&gt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.tag.begin.subrip</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&lt;/b&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>markup.tag.end.subrip</string>
				</dict>
			</dict>
			<key>name</key>
			<string>markup.bold.subrip</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\d+$</string>
			<key>name</key>
			<string>markup.number.subrip</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>markup.timing.start.subrip</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>markup.punctuation.subrip</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.timing.end.subrip</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\d\d:\d\d:\d\d,\d\d\d) (--&gt;) (\d\d:\d\d:\d\d,\d\d\d)$</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.subrip</string>
</dict>
</plist>